import type { Metadata } from "next";
import { headers } from "next/headers";
import { Analytics } from "@vercel/analytics/next";
import { TooltipProvider } from "@/components/ui/tooltip";
import "./globals.css";

const siteUrl =
  process.env.APP_URL ??
  (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : "http://localhost:3000");

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: "Devion's AI Twin | Devion Tharpe",
  description:
    "Explore Senior Solutions Engineer Devion Tharpe's AI case studies, experience, and technical approach through an interactive portfolio.",
  keywords: [
    "Devion Tharpe",
    "Senior Solutions Engineer",
    "AI agents",
    "Solutions Engineering",
    "Austin",
  ],
  authors: [{ name: "Devion Tharpe" }],
  robots: {
    index: true,
    follow: true,
  },
  openGraph: {
    title: "Devion's AI Twin | Devion Tharpe",
    description:
      "See how Devion turns customer problems into production-minded AI solutions.",
    type: "website",
    url: "/",
    siteName: "Devion's AI Twin",
  },
  twitter: {
    card: "summary_large_image",
    title: "Devion's AI Twin | Senior Solutions Engineer",
    description:
      "AI case studies, architecture, and experience from Devion Tharpe.",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Reading request headers opts the app into dynamic rendering so Next.js can
  // attach the per-request CSP nonce generated by src/proxy.ts.
  await headers();

  return (
    <html
      lang="en"
      className="dark h-full antialiased"
      suppressHydrationWarning
    >
      <body className="h-full">
        <TooltipProvider>{children}</TooltipProvider>
        <Analytics />
      </body>
    </html>
  );
}
